
struct token_node
{
  char line_number[10];
  char kind[20];
  char value[20];
  struct token_node * next;
};

struct syntax_node
{
  struct syntax_node * child[10];

  char kind_name[20];
};

extern struct token_node * current_token;

void chushihua_t(struct syntax_node *t);
struct syntax_node * chenghao();
struct syntax_node * chuhao();
struct syntax_node * jiahao();
struct syntax_node * jianhao();
struct syntax_node * xiaoyuhao();
struct syntax_node * denghao();
struct syntax_node * rev_if();
struct syntax_node * rev_then();
struct syntax_node * rev_else();
struct syntax_node * rev_fi();
struct syntax_node * rev_while();
struct syntax_node * rev_do();
struct syntax_node * rev_endwh();
struct syntax_node * rev_read();
struct syntax_node * dianhao();
struct syntax_node * act_param_list();
struct syntax_node * act_param_more();
struct syntax_node * add_op();
struct syntax_node * array_type();
struct syntax_node * ass_call();
struct syntax_node * assignment_rest();
struct syntax_node * base_type();
struct syntax_node * call_stm_rest();
struct syntax_node * cmp_op();
struct syntax_node * conditional_stm();
struct syntax_node * declare_part();
struct syntax_node * denghao();
struct syntax_node * douhao();
struct syntax_node * Exp();
struct syntax_node * factor();
struct syntax_node * fenhao();
struct syntax_node * fid_more();
struct syntax_node * field_var();
struct syntax_node * field_var_more();
struct syntax_node * form_list();
struct syntax_node * id();
struct syntax_node * id_program_name();
struct syntax_node * id_type_id();
struct syntax_node * input_stm();
struct syntax_node * intc();
struct syntax_node * invar();
struct syntax_node * loop_stm();
struct syntax_node * low();
struct syntax_node * maodenghao();
struct syntax_node * mult_op();
struct syntax_node * other_factor();
struct syntax_node * other_rel_e();
struct syntax_node * other_term();
struct syntax_node * output_stm();
struct syntax_node * param();
struct syntax_node * param_dec_list();
struct syntax_node * param_list();
struct syntax_node * param_more();
struct syntax_node * parse();
struct syntax_node * proc_dec();
struct syntax_node * proc_body();
struct syntax_node * proc_dec();
struct syntax_node * proc_dec_more();
struct syntax_node * proc_dec_part();
struct syntax_node * proc_decpart();
struct syntax_node * proc_name();
struct syntax_node * program();
struct syntax_node * program_body();
struct syntax_node * program_head();
struct syntax_node * program_name();
struct syntax_node * rel_exp();
struct syntax_node * return_stm();
struct syntax_node * rev_array();
struct syntax_node * rev_base_type();
struct syntax_node * rev_begin();
struct syntax_node * rev_end();
struct syntax_node * rev_of();
struct syntax_node * rev_procedure();
struct syntax_node * rev_program();
struct syntax_node * rev_return();
struct syntax_node * rev_type();
struct syntax_node * rev_var();
struct syntax_node * rev_write();
struct syntax_node * shuangdian();
struct syntax_node * stm();
struct syntax_node * stm_list();
struct syntax_node * stm_more();
struct syntax_node * structure_type();
struct syntax_node * term();
struct syntax_node * top();
struct syntax_node * type_dec();
struct syntax_node * type_dec_list();
struct syntax_node * type_dec_more();
struct syntax_node * type_decpart();
struct syntax_node * type_def();
struct syntax_node * type_id();
struct syntax_node * var_dec();
struct syntax_node * var_dec_list();
struct syntax_node * var_dec_more();
struct syntax_node * var_decpart();
struct syntax_node * var_id_list();
struct syntax_node * var_id_more();
struct syntax_node * vari_more();
struct syntax_node * variable();
struct syntax_node * youfangkuo();
struct syntax_node * youkuohao();
struct syntax_node * zuofangkuo();
struct syntax_node * zuokuohao();

void print_tree(struct syntax_node * t, int deep);